import type { AiModel } from '../types/ai'

// Generated by scripts/sync-cherry-ai-defaults.mjs from Cherry Studio defaults.
// Do not edit provider/model entries manually; update the source sync mapping instead.

const SYSTEM_DEFAULT_MODELS: AiModel[] = [
  {
    id: '302ai:deepseek-chat',
    label: 'deepseek-chat',
    description: 'Cherry Studio: DeepSeek',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:deepseek-reasoner',
    label: 'deepseek-reasoner',
    description: 'Cherry Studio: DeepSeek',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:chatgpt-4o-latest',
    label: 'chatgpt-4o-latest',
    description: 'Cherry Studio: OpenAI',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:gpt-4.1',
    label: 'gpt-4.1',
    description: 'Cherry Studio: OpenAI',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:o3',
    label: 'o3',
    description: 'Cherry Studio: OpenAI',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:o4-mini',
    label: 'o4-mini',
    description: 'Cherry Studio: OpenAI',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:qwen3-235b-a22b',
    label: 'qwen3-235b-a22b',
    description: 'Cherry Studio: Qwen',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:gemini-2.5-flash-preview-05-20',
    label: 'gemini-2.5-flash-preview-05-20',
    description: 'Cherry Studio: Gemini',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:gemini-2.5-pro-preview-06-05',
    label: 'gemini-2.5-pro-preview-06-05',
    description: 'Cherry Studio: Gemini',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:claude-sonnet-4-20250514',
    label: 'claude-sonnet-4-20250514',
    description: 'Cherry Studio: Anthropic',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:claude-opus-4-20250514',
    label: 'claude-opus-4-20250514',
    description: 'Cherry Studio: Anthropic',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:jina-clip-v2',
    label: 'jina-clip-v2',
    description: 'Cherry Studio: Jina AI',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: '302ai:jina-reranker-m0',
    label: 'jina-reranker-m0',
    description: 'Cherry Studio: Jina AI',
    providerRef: '302ai',
    providerLabel: '302ai'
  },
  {
    id: 'ph8:deepseek-v3-241226',
    label: 'deepseek-v3-241226',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ph8',
    providerLabel: 'ph8'
  },
  {
    id: 'ph8:deepseek-r1-250120',
    label: 'deepseek-r1-250120',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ph8',
    providerLabel: 'ph8'
  },
  {
    id: 'aihubmix:gpt-5',
    label: 'gpt-5',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-5-mini',
    label: 'gpt-5-mini',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-5-nano',
    label: 'gpt-5-nano',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-5-chat-latest',
    label: 'gpt-5-chat-latest',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:o3',
    label: 'o3',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:o4-mini',
    label: 'o4-mini',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-4.1',
    label: 'gpt-4.1',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-4o',
    label: 'gpt-4o',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-image-1',
    label: 'gpt-image-1',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gpt-image-2',
    label: 'gpt-image-2',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:DeepSeek-V3',
    label: 'DeepSeek-V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:DeepSeek-R1',
    label: 'DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:claude-sonnet-4-20250514',
    label: 'claude-sonnet-4-20250514',
    description: 'Cherry Studio: Claude',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gemini-2.5-pro',
    label: 'gemini-2.5-pro',
    description: 'Cherry Studio: Gemini',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gemini-2.5-flash-nothink',
    label: 'gemini-2.5-flash-nothink',
    description: 'Cherry Studio: Gemini',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:gemini-2.5-flash',
    label: 'gemini-2.5-flash',
    description: 'Cherry Studio: Gemini',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:Qwen3-235B-A22B-Instruct-2507',
    label: 'Qwen3-235B-A22B-Instruct-2507',
    description: 'Cherry Studio: qwen',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:kimi-k2-0711-preview',
    label: 'kimi-k2-0711-preview',
    description: 'Cherry Studio: moonshot',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:Llama-4-Scout-17B-16E-Instruct',
    label: 'Llama-4-Scout-17B-16E-Instruct',
    description: 'Cherry Studio: llama',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'aihubmix:Llama-4-Maverick-17B-128E-Instruct-FP8',
    label: 'Llama-4-Maverick-17B-128E-Instruct-FP8',
    description: 'Cherry Studio: llama',
    providerRef: 'aihubmix',
    providerLabel: 'aihubmix'
  },
  {
    id: 'burncloud:claude-opus-4-5-20251101',
    label: 'Claude 4.5 Opus',
    description: 'Cherry Studio: Claude 4.5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:claude-sonnet-4-5-20250929',
    label: 'Claude 4.5 Sonnet',
    description: 'Cherry Studio: Claude 4.5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:claude-haiku-4-5-20251001',
    label: 'Claude 4.5 Haiku',
    description: 'Cherry Studio: Claude 4.5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:gpt-5',
    label: 'GPT 5',
    description: 'Cherry Studio: GPT 5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:gpt-5.1',
    label: 'GPT 5.1',
    description: 'Cherry Studio: GPT 5.1',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    description: 'Cherry Studio: Gemini 2.5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:gemini-2.5-flash-image',
    label: 'Gemini 2.5 Flash Image',
    description: 'Cherry Studio: Gemini 2.5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    description: 'Cherry Studio: Gemini 2.5',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:gemini-3-pro-preview',
    label: 'Gemini 3 Pro Preview',
    description: 'Cherry Studio: Gemini 3',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:deepseek-reasoner',
    label: 'DeepSeek Reasoner',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'burncloud:deepseek-chat',
    label: 'DeepSeek Chat',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'burncloud',
    providerLabel: 'burncloud'
  },
  {
    id: 'silicon:deepseek-ai/DeepSeek-V3.2',
    label: 'deepseek-ai/DeepSeek-V3.2',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'silicon',
    providerLabel: 'silicon'
  },
  {
    id: 'silicon:Qwen/Qwen3-8B',
    label: 'Qwen/Qwen3-8B',
    description: 'Cherry Studio: Qwen',
    providerRef: 'silicon',
    providerLabel: 'silicon'
  },
  {
    id: 'silicon:BAAI/bge-m3',
    label: 'BAAI/bge-m3',
    description: 'Cherry Studio: BAAI',
    providerRef: 'silicon',
    providerLabel: 'silicon'
  },
  {
    id: 'ppio:deepseek/deepseek-v3.2',
    label: 'DeepSeek V3.2',
    description: 'Cherry Studio: deepseek',
    providerRef: 'ppio',
    providerLabel: 'ppio'
  },
  {
    id: 'ppio:minimax/minimax-m2',
    label: 'MiniMax M2',
    description: 'Cherry Studio: minimaxai',
    providerRef: 'ppio',
    providerLabel: 'ppio'
  },
  {
    id: 'ppio:qwen/qwen3-235b-a22b-instruct-2507',
    label: 'Qwen3-235b-a22b-instruct-2507',
    description: 'Cherry Studio: qwen',
    providerRef: 'ppio',
    providerLabel: 'ppio'
  },
  {
    id: 'ppio:qwen/qwen3-vl-235b-a22b-instruct',
    label: 'Qwen3-vl-235b-a22b-instruct',
    description: 'Cherry Studio: qwen',
    providerRef: 'ppio',
    providerLabel: 'ppio'
  },
  {
    id: 'ppio:qwen/qwen3-embedding-8b',
    label: 'Qwen3 Embedding 8B',
    description: 'Cherry Studio: qwen',
    providerRef: 'ppio',
    providerLabel: 'ppio'
  },
  {
    id: 'ppio:qwen/qwen3-reranker-8b',
    label: 'Qwen3 Reranker 8B',
    description: 'Cherry Studio: qwen',
    providerRef: 'ppio',
    providerLabel: 'ppio'
  },
  {
    id: 'openai:gpt-5.4',
    label: 'GPT 5.4',
    description: 'Cherry Studio: gpt-5.4',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5.4-pro',
    label: 'GPT 5.4 Pro',
    description: 'Cherry Studio: gpt-5.4',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5.2',
    label: 'GPT 5.2',
    description: 'Cherry Studio: gpt-5.2',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5.2-pro',
    label: 'GPT 5.2 Pro',
    description: 'Cherry Studio: gpt-5.2',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5.1',
    label: 'GPT 5.1',
    description: 'Cherry Studio: gpt-5.1',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5',
    label: 'GPT 5',
    description: 'Cherry Studio: gpt-5',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5-pro',
    label: 'GPT 5 Pro',
    description: 'Cherry Studio: gpt-5',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-5-chat',
    label: 'GPT 5 Chat',
    description: 'Cherry Studio: gpt-5',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'openai:gpt-image-1',
    label: 'GPT Image 1',
    description: 'Cherry Studio: gpt-image',
    providerRef: 'openai',
    providerLabel: 'openai'
  },
  {
    id: 'azure-openai:gpt-4o',
    label: 'GPT-4o',
    description: 'Cherry Studio: GPT 4o',
    providerRef: 'azure-openai',
    providerLabel: 'azure-openai'
  },
  {
    id: 'azure-openai:gpt-4o-mini',
    label: 'GPT-4o-mini',
    description: 'Cherry Studio: GPT 4o',
    providerRef: 'azure-openai',
    providerLabel: 'azure-openai'
  },
  {
    id: 'gemini:gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    description: 'Cherry Studio: Gemini 2.5',
    providerRef: 'gemini',
    providerLabel: 'gemini'
  },
  {
    id: 'gemini:gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    description: 'Cherry Studio: Gemini 2.5',
    providerRef: 'gemini',
    providerLabel: 'gemini'
  },
  {
    id: 'gemini:gemini-2.5-flash-image-preview',
    label: 'Gemini 2.5 Flash Image',
    description: 'Cherry Studio: Gemini 2.5',
    providerRef: 'gemini',
    providerLabel: 'gemini'
  },
  {
    id: 'gemini:gemini-3-pro-image-preview',
    label: 'Gemini 3 Pro Image Preview',
    description: 'Cherry Studio: Gemini 3',
    providerRef: 'gemini',
    providerLabel: 'gemini'
  },
  {
    id: 'gemini:gemini-3-pro-preview',
    label: 'Gemini 3 Pro Preview',
    description: 'Cherry Studio: Gemini 3',
    providerRef: 'gemini',
    providerLabel: 'gemini'
  },
  {
    id: 'gemini:gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro Preview',
    description: 'Cherry Studio: Gemini 3',
    providerRef: 'gemini',
    providerLabel: 'gemini'
  },
  {
    id: 'anthropic:claude-opus-4-7',
    label: 'Claude Opus 4.7',
    description: 'Cherry Studio: Claude 4.7',
    providerRef: 'anthropic',
    providerLabel: 'anthropic'
  },
  {
    id: 'anthropic:claude-opus-4-6',
    label: 'Claude Opus 4.6',
    description: 'Cherry Studio: Claude 4.6',
    providerRef: 'anthropic',
    providerLabel: 'anthropic'
  },
  {
    id: 'anthropic:claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6',
    description: 'Cherry Studio: Claude 4.6',
    providerRef: 'anthropic',
    providerLabel: 'anthropic'
  },
  {
    id: 'anthropic:claude-sonnet-4-5',
    label: 'Claude Sonnet 4.5',
    description: 'Cherry Studio: Claude 4.5',
    providerRef: 'anthropic',
    providerLabel: 'anthropic'
  },
  {
    id: 'anthropic:claude-haiku-4-5',
    label: 'Claude Haiku 4.5',
    description: 'Cherry Studio: Claude 4.5',
    providerRef: 'anthropic',
    providerLabel: 'anthropic'
  },
  {
    id: 'anthropic:claude-opus-4-5',
    label: 'Claude Opus 4.5',
    description: 'Cherry Studio: Claude 4.5',
    providerRef: 'anthropic',
    providerLabel: 'anthropic'
  },
  {
    id: 'deepseek:deepseek-v4-flash',
    label: 'deepseek-v4-flash',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'deepseek',
    providerLabel: 'deepseek'
  },
  {
    id: 'deepseek:deepseek-v4-pro',
    label: 'deepseek-v4-pro',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'deepseek',
    providerLabel: 'deepseek'
  },
  {
    id: 'together:meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo',
    label: 'Llama-3.2-11B-Vision',
    description: 'Cherry Studio: Llama-3.2',
    providerRef: 'together',
    providerLabel: 'together'
  },
  {
    id: 'together:meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo',
    label: 'Llama-3.2-90B-Vision',
    description: 'Cherry Studio: Llama-3.2',
    providerRef: 'together',
    providerLabel: 'together'
  },
  {
    id: 'together:google/gemma-2-27b-it',
    label: 'gemma-2-27b-it',
    description: 'Cherry Studio: Gemma',
    providerRef: 'together',
    providerLabel: 'together'
  },
  {
    id: 'together:google/gemma-2-9b-it',
    label: 'gemma-2-9b-it',
    description: 'Cherry Studio: Gemma',
    providerRef: 'together',
    providerLabel: 'together'
  },
  {
    id: 'ocoolai:deepseek-chat',
    label: 'deepseek-chat',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:deepseek-reasoner',
    label: 'deepseek-reasoner',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:deepseek-ai/DeepSeek-R1',
    label: 'deepseek-ai/DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:HiSpeed/DeepSeek-R1',
    label: 'HiSpeed/DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:ocoolAI/DeepSeek-R1',
    label: 'ocoolAI/DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:Azure/DeepSeek-R1',
    label: 'Azure/DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:gpt-4o',
    label: 'gpt-4o',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:gpt-4o-all',
    label: 'gpt-4o-all',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:gpt-4o-mini',
    label: 'gpt-4o-mini',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:gpt-4',
    label: 'gpt-4',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:o1-preview',
    label: 'o1-preview',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:o1-mini',
    label: 'o1-mini',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:claude-3-5-sonnet-20240620',
    label: 'claude-3-5-sonnet-20240620',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:claude-3-5-haiku-20241022',
    label: 'claude-3-5-haiku-20241022',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:gemini-pro',
    label: 'gemini-pro',
    description: 'Cherry Studio: Gemini',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:gemini-1.5-pro',
    label: 'gemini-1.5-pro',
    description: 'Cherry Studio: Gemini',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo',
    label: 'Llama-3.2-90B-Vision-Instruct-Turbo',
    description: 'Cherry Studio: Llama-3.2',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo',
    label: 'Llama-3.2-11B-Vision-Instruct-Turbo',
    description: 'Cherry Studio: Llama-3.2',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:meta-llama/Llama-3.2-3B-Vision-Instruct-Turbo',
    label: 'Llama-3.2-3B-Vision-Instruct-Turbo',
    description: 'Cherry Studio: Llama-3.2',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:google/gemma-2-27b-it',
    label: 'gemma-2-27b-it',
    description: 'Cherry Studio: Gemma',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:google/gemma-2-9b-it',
    label: 'gemma-2-9b-it',
    description: 'Cherry Studio: Gemma',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:Doubao-embedding',
    label: 'Doubao-embedding',
    description: 'Cherry Studio: Doubao',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:text-embedding-3-large',
    label: 'text-embedding-3-large',
    description: 'Cherry Studio: Embedding',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:text-embedding-3-small',
    label: 'text-embedding-3-small',
    description: 'Cherry Studio: Embedding',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'ocoolai:text-embedding-v2',
    label: 'text-embedding-v2',
    description: 'Cherry Studio: Embedding',
    providerRef: 'ocoolai',
    providerLabel: 'ocoolai'
  },
  {
    id: 'github:gpt-4o',
    label: 'OpenAI GPT-4o',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'github',
    providerLabel: 'github'
  },
  {
    id: 'copilot:gpt-5-mini',
    label: 'gpt-5-mini',
    description: 'Cherry Studio: copilot',
    providerRef: 'copilot',
    providerLabel: 'copilot'
  },
  {
    id: 'yi:yi-lightning',
    label: 'Yi Lightning',
    description: 'Cherry Studio: yi-lightning',
    providerRef: 'yi',
    providerLabel: 'yi'
  },
  {
    id: 'yi:yi-vision-v2',
    label: 'Yi Vision v2',
    description: 'Cherry Studio: yi-vision',
    providerRef: 'yi',
    providerLabel: 'yi'
  },
  {
    id: 'zhipu:glm-5',
    label: 'GLM-5',
    description: 'Cherry Studio: GLM-5',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.7',
    label: 'GLM-4.7',
    description: 'Cherry Studio: GLM-4.7',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.5-flash',
    label: 'GLM-4.5-Flash',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.6',
    label: 'GLM-4.6',
    description: 'Cherry Studio: GLM-4.6',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.6v',
    label: 'GLM-4.6V',
    description: 'Cherry Studio: GLM-4.6V',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.6v-flash',
    label: 'GLM-4.6V-Flash',
    description: 'Cherry Studio: GLM-4.6V',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.6v-flashx',
    label: 'GLM-4.6V-FlashX',
    description: 'Cherry Studio: GLM-4.6V',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.5',
    label: 'GLM-4.5',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.5-air',
    label: 'GLM-4.5-Air',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.5-airx',
    label: 'GLM-4.5-AirX',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:glm-4.5v',
    label: 'GLM-4.5V',
    description: 'Cherry Studio: GLM-4.5V',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:embedding-3',
    label: 'Embedding-3',
    description: 'Cherry Studio: Embedding',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'zhipu:cogView-4-250304',
    label: 'cogView-4',
    description: 'Cherry Studio: cogView',
    providerRef: 'zhipu',
    providerLabel: 'zhipu'
  },
  {
    id: 'moonshot:moonshot-v1-auto',
    label: 'moonshot-v1-auto',
    description: 'Cherry Studio: moonshot-v1',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2-0711-preview',
    label: 'kimi-k2-0711-preview',
    description: 'Cherry Studio: kimi-k2',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2.5',
    label: 'Kimi K2.5',
    description: 'Cherry Studio: Kimi K2.5',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'vision'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2.6',
    label: 'Kimi K2.6',
    description: 'Cherry Studio: Kimi K2.6',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'vision'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2-0905-Preview',
    label: 'Kimi K2 0905 Preview',
    description: 'Cherry Studio: Kimi K2',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2-turbo-preview',
    label: 'Kimi K2 Turbo Preview',
    description: 'Cherry Studio: Kimi K2',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2-thinking',
    label: 'Kimi K2 Thinking',
    description: 'Cherry Studio: Kimi K2 Thinking',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'moonshot:kimi-k2-thinking-turbo',
    label: 'Kimi K2 Thinking Turbo',
    description: 'Cherry Studio: Kimi K2 Thinking',
    providerRef: 'moonshot',
    providerLabel: 'moonshot',
    capabilities: [
      {
        type: 'text'
      },
      {
        type: 'function_calling'
      }
    ]
  },
  {
    id: 'baichuan:Baichuan4',
    label: 'Baichuan4',
    description: 'Cherry Studio: Baichuan4',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan3-Turbo',
    label: 'Baichuan3 Turbo',
    description: 'Cherry Studio: Baichuan3',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan3-Turbo-128k',
    label: 'Baichuan3 Turbo 128k',
    description: 'Cherry Studio: Baichuan3',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan4-Turbo',
    label: 'Baichuan4 Turbo',
    description: 'Cherry Studio: Baichuan4',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan4-Air',
    label: 'Baichuan4 Air',
    description: 'Cherry Studio: Baichuan4',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan-M2',
    label: 'Baichuan M2',
    description: 'Cherry Studio: Baichuan-M2',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan-M2-Plus',
    label: 'Baichuan M2 Plus',
    description: 'Cherry Studio: Baichuan-M2',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan-M3',
    label: 'Baichuan M3',
    description: 'Cherry Studio: Baichuan-M3',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'baichuan:Baichuan-M3-Plus',
    label: 'Baichuan M3 Plus',
    description: 'Cherry Studio: Baichuan-M3',
    providerRef: 'baichuan',
    providerLabel: 'baichuan'
  },
  {
    id: 'modelscope:Qwen/Qwen2.5-72B-Instruct',
    label: 'Qwen/Qwen2.5-72B-Instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'modelscope',
    providerLabel: 'modelscope'
  },
  {
    id: 'modelscope:Qwen/Qwen2.5-VL-72B-Instruct',
    label: 'Qwen/Qwen2.5-VL-72B-Instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'modelscope',
    providerLabel: 'modelscope'
  },
  {
    id: 'modelscope:Qwen/Qwen2.5-Coder-32B-Instruct',
    label: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'modelscope',
    providerLabel: 'modelscope'
  },
  {
    id: 'modelscope:deepseek-ai/DeepSeek-R1',
    label: 'deepseek-ai/DeepSeek-R1',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'modelscope',
    providerLabel: 'modelscope'
  },
  {
    id: 'modelscope:deepseek-ai/DeepSeek-V3',
    label: 'deepseek-ai/DeepSeek-V3',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'modelscope',
    providerLabel: 'modelscope'
  },
  {
    id: 'dashscope:qwen3.5-plus',
    label: 'Qwen3.5-Plus',
    description: 'Cherry Studio: Qwen',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'dashscope:qwen3.5-flash',
    label: 'Qwen3.5-Flash',
    description: 'Cherry Studio: Qwen',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'dashscope:qwen3-max',
    label: 'Qwen3-Max',
    description: 'Cherry Studio: Qwen',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'dashscope:kimi-k2.5',
    label: 'Kimi K2.5',
    description: 'Cherry Studio: Kimi',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'dashscope:glm-5',
    label: 'GLM-5',
    description: 'Cherry Studio: GLM',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'dashscope:MiniMax/MiniMax-M2.5',
    label: 'MiniMax M2.5',
    description: 'Cherry Studio: MiniMax',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'dashscope:deepseek-v3.2',
    label: 'DeepSeek V3.2',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'dashscope',
    providerLabel: 'dashscope'
  },
  {
    id: 'stepfun:step-1-8k',
    label: 'Step 1 8K',
    description: 'Cherry Studio: Step 1',
    providerRef: 'stepfun',
    providerLabel: 'stepfun'
  },
  {
    id: 'stepfun:step-1-flash',
    label: 'Step 1 Flash',
    description: 'Cherry Studio: Step 1',
    providerRef: 'stepfun',
    providerLabel: 'stepfun'
  },
  {
    id: 'doubao:doubao-seed-1-8-251228',
    label: 'Doubao-Seed-1.8',
    description: 'Cherry Studio: Doubao-Seed-1.8',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-1-5-vision-pro-32k-250115',
    label: 'doubao-1.5-vision-pro',
    description: 'Cherry Studio: Doubao-1.5-vision-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-1-5-pro-32k-250115',
    label: 'doubao-1.5-pro-32k',
    description: 'Cherry Studio: Doubao-1.5-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-1-5-pro-32k-character-250228',
    label: 'doubao-1.5-pro-32k-character',
    description: 'Cherry Studio: Doubao-1.5-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-1-5-pro-256k-250115',
    label: 'Doubao-1.5-pro-256k',
    description: 'Cherry Studio: Doubao-1.5-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:deepseek-r1-250120',
    label: 'DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:deepseek-r1-distill-qwen-32b-250120',
    label: 'DeepSeek-R1-Distill-Qwen-32B',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:deepseek-r1-distill-qwen-7b-250120',
    label: 'DeepSeek-R1-Distill-Qwen-7B',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:deepseek-v3-250324',
    label: 'DeepSeek-V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-pro-32k-241215',
    label: 'Doubao-pro-32k',
    description: 'Cherry Studio: Doubao-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-pro-32k-functioncall-241028',
    label: 'Doubao-pro-32k-functioncall-241028',
    description: 'Cherry Studio: Doubao-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-pro-32k-character-241215',
    label: 'Doubao-pro-32k-character-241215',
    description: 'Cherry Studio: Doubao-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-pro-256k-241115',
    label: 'Doubao-pro-256k',
    description: 'Cherry Studio: Doubao-pro',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-lite-4k-character-240828',
    label: 'Doubao-lite-4k-character-240828',
    description: 'Cherry Studio: Doubao-lite',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-lite-32k-240828',
    label: 'Doubao-lite-32k',
    description: 'Cherry Studio: Doubao-lite',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-lite-32k-character-241015',
    label: 'Doubao-lite-32k-character-241015',
    description: 'Cherry Studio: Doubao-lite',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-lite-128k-240828',
    label: 'Doubao-lite-128k',
    description: 'Cherry Studio: Doubao-lite',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-1-5-lite-32k-250115',
    label: 'Doubao-1.5-lite-32k',
    description: 'Cherry Studio: Doubao-lite',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-embedding-large-text-240915',
    label: 'Doubao-embedding-large',
    description: 'Cherry Studio: Doubao-embedding',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-embedding-text-240715',
    label: 'Doubao-embedding',
    description: 'Cherry Studio: Doubao-embedding',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-embedding-vision-241215',
    label: 'Doubao-embedding-vision',
    description: 'Cherry Studio: Doubao-embedding',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-vision-lite-32k-241015',
    label: 'Doubao-vision-lite-32k',
    description: 'Cherry Studio: Doubao-vision-lite-32k',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-seed-2-0-pro-260215',
    label: 'Doubao-Seed-2.0-Pro',
    description: 'Cherry Studio: Doubao-Seed-2.0',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-seed-2-0-lite-260215',
    label: 'Doubao-Seed-2.0-Lite',
    description: 'Cherry Studio: Doubao-Seed-2.0',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-seed-2-0-code-preview-260215',
    label: 'Doubao-Seed-2.0-Code-Preview',
    description: 'Cherry Studio: Doubao-Seed-2.0',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'doubao:doubao-seed-2-0-mini-260215',
    label: 'Doubao-Seed-2.0-Mini',
    description: 'Cherry Studio: Doubao-Seed-2.0',
    providerRef: 'doubao',
    providerLabel: 'doubao'
  },
  {
    id: 'minimax:MiniMax-M3',
    label: 'MiniMax-M3',
    description: 'Cherry Studio: M3',
    providerRef: 'minimax',
    providerLabel: 'minimax'
  },
  {
    id: 'minimax:MiniMax-M2.7',
    label: 'MiniMax-M2.7',
    description: 'Cherry Studio: M2.7',
    providerRef: 'minimax',
    providerLabel: 'minimax'
  },
  {
    id: 'minimax:MiniMax-M2.7-highspeed',
    label: 'MiniMax-M2.7-highspeed',
    description: 'Cherry Studio: M2.7',
    providerRef: 'minimax',
    providerLabel: 'minimax'
  },
  {
    id: 'minimax-global:MiniMax-M3',
    label: 'MiniMax-M3',
    description: 'Cherry Studio: M3',
    providerRef: 'minimax-global',
    providerLabel: 'minimax-global'
  },
  {
    id: 'minimax-global:MiniMax-M2.7',
    label: 'MiniMax-M2.7',
    description: 'Cherry Studio: M2.7',
    providerRef: 'minimax-global',
    providerLabel: 'minimax-global'
  },
  {
    id: 'minimax-global:MiniMax-M2.7-highspeed',
    label: 'MiniMax-M2.7-highspeed',
    description: 'Cherry Studio: M2.7',
    providerRef: 'minimax-global',
    providerLabel: 'minimax-global'
  },
  {
    id: 'hyperbolic:Qwen/Qwen2-VL-72B-Instruct',
    label: 'Qwen2-VL-72B-Instruct',
    description: 'Cherry Studio: Qwen2-VL',
    providerRef: 'hyperbolic',
    providerLabel: 'hyperbolic'
  },
  {
    id: 'hyperbolic:Qwen/Qwen2-VL-7B-Instruct',
    label: 'Qwen2-VL-7B-Instruct',
    description: 'Cherry Studio: Qwen2-VL',
    providerRef: 'hyperbolic',
    providerLabel: 'hyperbolic'
  },
  {
    id: 'hyperbolic:mistralai/Pixtral-12B-2409',
    label: 'Pixtral-12B-2409',
    description: 'Cherry Studio: Pixtral',
    providerRef: 'hyperbolic',
    providerLabel: 'hyperbolic'
  },
  {
    id: 'hyperbolic:meta-llama/Meta-Llama-3.1-405B',
    label: 'Meta-Llama-3.1-405B',
    description: 'Cherry Studio: Meta-Llama-3.1',
    providerRef: 'hyperbolic',
    providerLabel: 'hyperbolic'
  },
  {
    id: 'grok:grok-4.3',
    label: 'Grok 4.3',
    description: 'Cherry Studio: Grok',
    providerRef: 'grok',
    providerLabel: 'grok'
  },
  {
    id: 'grok:grok-4',
    label: 'Grok 4',
    description: 'Cherry Studio: Grok',
    providerRef: 'grok',
    providerLabel: 'grok'
  },
  {
    id: 'grok:grok-3',
    label: 'Grok 3',
    description: 'Cherry Studio: Grok',
    providerRef: 'grok',
    providerLabel: 'grok'
  },
  {
    id: 'grok:grok-3-fast',
    label: 'Grok 3 Fast',
    description: 'Cherry Studio: Grok',
    providerRef: 'grok',
    providerLabel: 'grok'
  },
  {
    id: 'grok:grok-3-mini',
    label: 'Grok 3 Mini',
    description: 'Cherry Studio: Grok',
    providerRef: 'grok',
    providerLabel: 'grok'
  },
  {
    id: 'grok:grok-3-mini-fast',
    label: 'Grok 3 Mini Fast',
    description: 'Cherry Studio: Grok',
    providerRef: 'grok',
    providerLabel: 'grok'
  },
  {
    id: 'mistral:pixtral-12b-2409',
    label: 'Pixtral 12B [Free]',
    description: 'Cherry Studio: Pixtral',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:pixtral-large-latest',
    label: 'Pixtral Large',
    description: 'Cherry Studio: Pixtral',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:ministral-3b-latest',
    label: 'Mistral 3B [Free]',
    description: 'Cherry Studio: Mistral Mini',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:ministral-8b-latest',
    label: 'Mistral 8B [Free]',
    description: 'Cherry Studio: Mistral Mini',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:codestral-latest',
    label: 'Mistral Codestral',
    description: 'Cherry Studio: Mistral Code',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:mistral-large-latest',
    label: 'Mistral Large',
    description: 'Cherry Studio: Mistral Chat',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:mistral-small-latest',
    label: 'Mistral Small',
    description: 'Cherry Studio: Mistral Chat',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:open-mistral-nemo',
    label: 'Mistral Nemo',
    description: 'Cherry Studio: Mistral Chat',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'mistral:mistral-embed',
    label: 'Mistral Embedding',
    description: 'Cherry Studio: Mistral Embed',
    providerRef: 'mistral',
    providerLabel: 'mistral'
  },
  {
    id: 'jina:jina-clip-v1',
    label: 'jina-clip-v1',
    description: 'Cherry Studio: Jina Clip',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-clip-v2',
    label: 'jina-clip-v2',
    description: 'Cherry Studio: Jina Clip',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-embeddings-v2-base-en',
    label: 'jina-embeddings-v2-base-en',
    description: 'Cherry Studio: Jina Embeddings V2',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-embeddings-v2-base-es',
    label: 'jina-embeddings-v2-base-es',
    description: 'Cherry Studio: Jina Embeddings V2',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-embeddings-v2-base-de',
    label: 'jina-embeddings-v2-base-de',
    description: 'Cherry Studio: Jina Embeddings V2',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-embeddings-v2-base-zh',
    label: 'jina-embeddings-v2-base-zh',
    description: 'Cherry Studio: Jina Embeddings V2',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-embeddings-v2-base-code',
    label: 'jina-embeddings-v2-base-code',
    description: 'Cherry Studio: Jina Embeddings V2',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'jina:jina-embeddings-v3',
    label: 'jina-embeddings-v3',
    description: 'Cherry Studio: Jina Embeddings V3',
    providerRef: 'jina',
    providerLabel: 'jina'
  },
  {
    id: 'fireworks:accounts/fireworks/models/mythomax-l2-13b',
    label: 'mythomax-l2-13b',
    description: 'Cherry Studio: Gryphe',
    providerRef: 'fireworks',
    providerLabel: 'fireworks'
  },
  {
    id: 'fireworks:accounts/fireworks/models/llama-v3-70b-instruct',
    label: 'Llama-3-70B-Instruct',
    description: 'Cherry Studio: Llama3',
    providerRef: 'fireworks',
    providerLabel: 'fireworks'
  },
  {
    id: 'hunyuan:hunyuan-pro',
    label: 'hunyuan-pro',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-standard',
    label: 'hunyuan-standard',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-lite',
    label: 'hunyuan-lite',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-standard-256k',
    label: 'hunyuan-standard-256k',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-vision',
    label: 'hunyuan-vision',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-code',
    label: 'hunyuan-code',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-role',
    label: 'hunyuan-role',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-turbo',
    label: 'hunyuan-turbo',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-turbos-latest',
    label: 'hunyuan-turbos-latest',
    description: 'Cherry Studio: Hunyuan',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'hunyuan:hunyuan-embedding',
    label: 'hunyuan-embedding',
    description: 'Cherry Studio: Embedding',
    providerRef: 'hunyuan',
    providerLabel: 'hunyuan'
  },
  {
    id: 'nvidia:01-ai/yi-large',
    label: 'yi-large',
    description: 'Cherry Studio: Yi',
    providerRef: 'nvidia',
    providerLabel: 'nvidia'
  },
  {
    id: 'nvidia:meta/llama-3.1-405b-instruct',
    label: 'llama-3.1-405b-instruct',
    description: 'Cherry Studio: llama-3.1',
    providerRef: 'nvidia',
    providerLabel: 'nvidia'
  },
  {
    id: 'openrouter:google/gemini-2.5-flash-image-preview',
    label: 'Google: Gemini 2.5 Flash Image',
    description: 'Cherry Studio: google',
    providerRef: 'openrouter',
    providerLabel: 'openrouter'
  },
  {
    id: 'openrouter:google/gemini-2.5-flash-preview',
    label: 'Google: Gemini 2.5 Flash Preview',
    description: 'Cherry Studio: google',
    providerRef: 'openrouter',
    providerLabel: 'openrouter'
  },
  {
    id: 'openrouter:qwen/qwen-2.5-7b-instruct:free',
    label: 'Qwen: Qwen-2.5-7B Instruct',
    description: 'Cherry Studio: qwen',
    providerRef: 'openrouter',
    providerLabel: 'openrouter'
  },
  {
    id: 'openrouter:deepseek/deepseek-chat',
    label: 'DeepSeek: V3',
    description: 'Cherry Studio: deepseek',
    providerRef: 'openrouter',
    providerLabel: 'openrouter'
  },
  {
    id: 'openrouter:mistralai/mistral-7b-instruct:free',
    label: 'Mistral: Mistral 7B Instruct',
    description: 'Cherry Studio: mistralai',
    providerRef: 'openrouter',
    providerLabel: 'openrouter'
  },
  {
    id: 'groq:llama3-8b-8192',
    label: 'LLaMA3 8B',
    description: 'Cherry Studio: Llama3',
    providerRef: 'groq',
    providerLabel: 'groq'
  },
  {
    id: 'groq:llama3-70b-8192',
    label: 'LLaMA3 70B',
    description: 'Cherry Studio: Llama3',
    providerRef: 'groq',
    providerLabel: 'groq'
  },
  {
    id: 'groq:mistral-saba-24b',
    label: 'Mistral Saba 24B',
    description: 'Cherry Studio: Mistral',
    providerRef: 'groq',
    providerLabel: 'groq'
  },
  {
    id: 'groq:gemma-9b-it',
    label: 'Gemma 9B',
    description: 'Cherry Studio: Gemma',
    providerRef: 'groq',
    providerLabel: 'groq'
  },
  {
    id: 'baidu-cloud:deepseek-r1',
    label: 'DeepSeek R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:deepseek-v3',
    label: 'DeepSeek V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:ernie-4.0-8k-latest',
    label: 'ERNIE-4.0',
    description: 'Cherry Studio: ERNIE',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:ernie-4.0-turbo-8k-latest',
    label: 'ERNIE 4.0 Trubo',
    description: 'Cherry Studio: ERNIE',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:ernie-speed-8k',
    label: 'ERNIE Speed',
    description: 'Cherry Studio: ERNIE',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:ernie-lite-8k',
    label: 'ERNIE Lite',
    description: 'Cherry Studio: ERNIE',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:bge-large-zh',
    label: 'BGE Large ZH',
    description: 'Cherry Studio: Embedding',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'baidu-cloud:bge-large-en',
    label: 'BGE Large EN',
    description: 'Cherry Studio: Embedding',
    providerRef: 'baidu-cloud',
    providerLabel: 'baidu-cloud'
  },
  {
    id: 'dmxapi:Qwen/Qwen2.5-7B-Instruct',
    label: 'Qwen/Qwen2.5-7B-Instruct',
    description: 'Cherry Studio: 免费模型',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:ERNIE-Speed-128K',
    label: 'ERNIE-Speed-128K',
    description: 'Cherry Studio: 免费模型',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:gpt-4o',
    label: 'gpt-4o',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:gpt-4o-mini',
    label: 'gpt-4o-mini',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:DMXAPI-DeepSeek-R1',
    label: 'DMXAPI-DeepSeek-R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:DMXAPI-DeepSeek-V3',
    label: 'DMXAPI-DeepSeek-V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:claude-3-5-sonnet-20241022',
    label: 'claude-3-5-sonnet-20241022',
    description: 'Cherry Studio: Claude',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'dmxapi:gemini-2.0-flash',
    label: 'gemini-2.0-flash',
    description: 'Cherry Studio: Gemini',
    providerRef: 'dmxapi',
    providerLabel: 'dmxapi'
  },
  {
    id: 'perplexity:sonar-reasoning-pro',
    label: 'sonar-reasoning-pro',
    description: 'Cherry Studio: Sonar',
    providerRef: 'perplexity',
    providerLabel: 'perplexity'
  },
  {
    id: 'perplexity:sonar-reasoning',
    label: 'sonar-reasoning',
    description: 'Cherry Studio: Sonar',
    providerRef: 'perplexity',
    providerLabel: 'perplexity'
  },
  {
    id: 'perplexity:sonar-pro',
    label: 'sonar-pro',
    description: 'Cherry Studio: Sonar',
    providerRef: 'perplexity',
    providerLabel: 'perplexity'
  },
  {
    id: 'perplexity:sonar',
    label: 'sonar',
    description: 'Cherry Studio: Sonar',
    providerRef: 'perplexity',
    providerLabel: 'perplexity'
  },
  {
    id: 'perplexity:sonar-deep-research',
    label: 'sonar-deep-research',
    description: 'Cherry Studio: Sonar',
    providerRef: 'perplexity',
    providerLabel: 'perplexity'
  },
  {
    id: 'infini:deepseek-r1',
    label: 'deepseek-r1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:deepseek-r1-distill-qwen-32b',
    label: 'deepseek-r1-distill-qwen-32b',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:deepseek-v3',
    label: 'deepseek-v3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwen2.5-72b-instruct',
    label: 'qwen2.5-72b-instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwen2.5-32b-instruct',
    label: 'qwen2.5-32b-instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwen2.5-14b-instruct',
    label: 'qwen2.5-14b-instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwen2.5-7b-instruct',
    label: 'qwen2.5-7b-instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwen2-72b-instruct',
    label: 'qwen2-72b-instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwq-32b-preview',
    label: 'qwq-32b-preview',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:qwen2.5-coder-32b-instruct',
    label: 'qwen2.5-coder-32b-instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:llama-3.3-70b-instruct',
    label: 'llama-3.3-70b-instruct',
    description: 'Cherry Studio: Llama',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:bge-m3',
    label: 'bge-m3',
    description: 'Cherry Studio: BAAI',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:gemma-2-27b-it',
    label: 'gemma-2-27b-it',
    description: 'Cherry Studio: Gemma',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:jina-embeddings-v2-base-zh',
    label: 'jina-embeddings-v2-base-zh',
    description: 'Cherry Studio: Jina',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'infini:jina-embeddings-v2-base-code',
    label: 'jina-embeddings-v2-base-code',
    description: 'Cherry Studio: Jina',
    providerRef: 'infini',
    providerLabel: 'infini'
  },
  {
    id: 'tencent-cloud-ti:deepseek-r1',
    label: 'DeepSeek R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'tencent-cloud-ti',
    providerLabel: 'tencent-cloud-ti'
  },
  {
    id: 'tencent-cloud-ti:deepseek-v3',
    label: 'DeepSeek V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'tencent-cloud-ti',
    providerLabel: 'tencent-cloud-ti'
  },
  {
    id: 'voyageai:voyage-3-large',
    label: 'voyage-3-large',
    description: 'Cherry Studio: Voyage Embeddings V3',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:voyage-3',
    label: 'voyage-3',
    description: 'Cherry Studio: Voyage Embeddings V3',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:voyage-3-lite',
    label: 'voyage-3-lite',
    description: 'Cherry Studio: Voyage Embeddings V3',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:voyage-code-3',
    label: 'voyage-code-3',
    description: 'Cherry Studio: Voyage Embeddings V3',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:voyage-finance-3',
    label: 'voyage-finance-3',
    description: 'Cherry Studio: Voyage Embeddings V2',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:voyage-law-2',
    label: 'voyage-law-2',
    description: 'Cherry Studio: Voyage Embeddings V2',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:voyage-code-2',
    label: 'voyage-code-2',
    description: 'Cherry Studio: Voyage Embeddings V2',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:rerank-2',
    label: 'rerank-2',
    description: 'Cherry Studio: Voyage Rerank V2',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'voyageai:rerank-2-lite',
    label: 'rerank-2-lite',
    description: 'Cherry Studio: Voyage Rerank V2',
    providerRef: 'voyageai',
    providerLabel: 'voyageai'
  },
  {
    id: 'qiniu:deepseek-r1',
    label: 'DeepSeek R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:deepseek-r1-search',
    label: 'DeepSeek R1 Search',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:deepseek-r1-32b',
    label: 'DeepSeek R1 32B',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:deepseek-v3',
    label: 'DeepSeek V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:deepseek-v3-search',
    label: 'DeepSeek V3 Search',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:deepseek-v3-tool',
    label: 'DeepSeek V3 Tool',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:qwq-32b',
    label: 'QWQ 32B',
    description: 'Cherry Studio: Qwen',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'qiniu:qwen2.5-72b-instruct',
    label: 'Qwen2.5 72B Instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'qiniu',
    providerLabel: 'qiniu'
  },
  {
    id: 'tokenflux:gpt-4.1',
    label: 'GPT-4.1',
    description: 'Cherry Studio: GPT-4.1',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:gpt-4.1-mini',
    label: 'GPT-4.1 Mini',
    description: 'Cherry Studio: GPT-4.1',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:claude-sonnet-4',
    label: 'Claude Sonnet 4',
    description: 'Cherry Studio: Claude',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:claude-3-7-sonnet',
    label: 'Claude 3.7 Sonnet',
    description: 'Cherry Studio: Claude',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    description: 'Cherry Studio: Gemini',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    description: 'Cherry Studio: Gemini',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:deepseek-r1',
    label: 'DeepSeek R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:deepseek-v3',
    label: 'DeepSeek V3',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:qwen-max',
    label: 'Qwen Max',
    description: 'Cherry Studio: Qwen',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'tokenflux:qwen-plus',
    label: 'Qwen Plus',
    description: 'Cherry Studio: Qwen',
    providerRef: 'tokenflux',
    providerLabel: 'tokenflux'
  },
  {
    id: 'cephalon:DeepSeek-R1',
    label: 'DeepSeek-R1满血版',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'cephalon',
    providerLabel: 'cephalon',
    capabilities: [
      {
        type: 'reasoning'
      }
    ]
  },
  {
    id: 'lanyun:/maas/deepseek-ai/DeepSeek-R1-0528',
    label: 'deepseek-ai/DeepSeek-R1',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'lanyun',
    providerLabel: 'lanyun'
  },
  {
    id: 'lanyun:/maas/deepseek-ai/DeepSeek-V3-0324',
    label: 'deepseek-ai/DeepSeek-V3',
    description: 'Cherry Studio: deepseek-ai',
    providerRef: 'lanyun',
    providerLabel: 'lanyun'
  },
  {
    id: 'lanyun:/maas/qwen/Qwen2.5-72B-Instruct',
    label: 'Qwen2.5-72B-Instruct',
    description: 'Cherry Studio: Qwen',
    providerRef: 'lanyun',
    providerLabel: 'lanyun'
  },
  {
    id: 'lanyun:/maas/qwen/Qwen3-235B-A22B',
    label: 'Qwen/Qwen3-235B',
    description: 'Cherry Studio: Qwen',
    providerRef: 'lanyun',
    providerLabel: 'lanyun'
  },
  {
    id: 'lanyun:/maas/minimax/MiniMax-M1-80k',
    label: 'MiniMax-M1-80k',
    description: 'Cherry Studio: MiniMax',
    providerRef: 'lanyun',
    providerLabel: 'lanyun'
  },
  {
    id: 'lanyun:/maas/google/Gemma3-27B',
    label: 'Gemma3-27B',
    description: 'Cherry Studio: google',
    providerRef: 'lanyun',
    providerLabel: 'lanyun'
  },
  {
    id: 'poe:Claude-Opus-4.6',
    label: 'Claude Opus 4.6',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:Claude-Sonnet-4.6',
    label: 'Claude Sonnet 4.6',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:Claude-Haiku-4.5',
    label: 'Claude Haiku 4.5',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:GPT-5.4',
    label: 'GPT 5.4',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:GPT-5.3-Codex',
    label: 'GPT 5.3 Codex',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:GPT-5.2',
    label: 'GPT 5.2',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:GPT-5.2-Codex',
    label: 'GPT 5.2 Codex',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:GPT-5.1',
    label: 'GPT 5.1',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:Gemini-3.1-Pro',
    label: 'Gemini 3.1 Pro',
    description: 'Cherry Studio: Google',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:Grok-4',
    label: 'Grok 4',
    description: 'Cherry Studio: xAI',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:DeepSeek-R1',
    label: 'DeepSeek R1',
    description: 'Cherry Studio: DeepSeek',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:Kimi-K2.5',
    label: 'Kimi K2.5',
    description: 'Cherry Studio: Kimi',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'poe:Kimi-K2-Thinking',
    label: 'Kimi K2 Thinking',
    description: 'Cherry Studio: Kimi',
    providerRef: 'poe',
    providerLabel: 'poe'
  },
  {
    id: 'aionly:claude-opus-4-6',
    label: 'Claude Opus 4.6',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:claude-haiku-4-5-20251001',
    label: 'Claude Haiku 4.5',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6',
    description: 'Cherry Studio: Anthropic',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gpt-5.4',
    label: 'GPT-5.4',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gpt-5.4-mini',
    label: 'GPT-5.4-MiNi',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gpt-5.4-nano',
    label: 'GPT-5.4-NaNo',
    description: 'Cherry Studio: OpenAI',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gemini-3.1-flash-lite-preview',
    label: 'Gemini 3.1 Flash-Lite',
    description: 'Cherry Studio: Google',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro Preview',
    description: 'Cherry Studio: Google',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    description: 'Cherry Studio: Google',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'aionly:gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    description: 'Cherry Studio: Google',
    providerRef: 'aionly',
    providerLabel: 'aionly'
  },
  {
    id: 'longcat:LongCat-Flash-Chat',
    label: 'LongCat Flash Chat',
    description: 'Cherry Studio: LongCat',
    providerRef: 'longcat',
    providerLabel: 'longcat'
  },
  {
    id: 'longcat:LongCat-Flash-Thinking',
    label: 'LongCat Flash Thinking',
    description: 'Cherry Studio: LongCat',
    providerRef: 'longcat',
    providerLabel: 'longcat'
  },
  {
    id: 'cerebras:gpt-oss-120b',
    label: 'GPT oss 120B',
    description: 'Cherry Studio: openai',
    providerRef: 'cerebras',
    providerLabel: 'cerebras'
  },
  {
    id: 'cerebras:zai-glm-4.6',
    label: 'GLM 4.6',
    description: 'Cherry Studio: zai',
    providerRef: 'cerebras',
    providerLabel: 'cerebras'
  },
  {
    id: 'cerebras:qwen-3-235b-a22b-instruct-2507',
    label: 'Qwen 3 235B A22B Instruct',
    description: 'Cherry Studio: qwen',
    providerRef: 'cerebras',
    providerLabel: 'cerebras'
  },
  {
    id: 'mimo:mimo-v2.5',
    label: 'Mimo V2.5',
    description: 'Cherry Studio: mimo',
    providerRef: 'mimo',
    providerLabel: 'mimo'
  },
  {
    id: 'mimo:mimo-v2.5-pro',
    label: 'Mimo V2.5 Pro',
    description: 'Cherry Studio: mimo',
    providerRef: 'mimo',
    providerLabel: 'mimo'
  },
  {
    id: 'mimo:mimo-v2-flash',
    label: 'Mimo V2 Flash',
    description: 'Cherry Studio: mimo',
    providerRef: 'mimo',
    providerLabel: 'mimo'
  },
  {
    id: 'mimo:mimo-v2-omni',
    label: 'Mimo V2 Omni',
    description: 'Cherry Studio: mimo',
    providerRef: 'mimo',
    providerLabel: 'mimo'
  },
  {
    id: 'zai:glm-5',
    label: 'GLM-5',
    description: 'Cherry Studio: GLM-5',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.7',
    label: 'GLM-4.7',
    description: 'Cherry Studio: GLM-4.7',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.5-flash',
    label: 'GLM-4.5-Flash',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.6',
    label: 'GLM-4.6',
    description: 'Cherry Studio: GLM-4.6',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.6v',
    label: 'GLM-4.6V',
    description: 'Cherry Studio: GLM-4.6V',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.6v-flash',
    label: 'GLM-4.6V-Flash',
    description: 'Cherry Studio: GLM-4.6V',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.5',
    label: 'GLM-4.5',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.5-air',
    label: 'GLM-4.5-Air',
    description: 'Cherry Studio: GLM-4.5',
    providerRef: 'zai',
    providerLabel: 'zai'
  },
  {
    id: 'zai:glm-4.5v',
    label: 'GLM-4.5V',
    description: 'Cherry Studio: GLM-4.5V',
    providerRef: 'zai',
    providerLabel: 'zai'
  }
]

function cloneModel(model: AiModel): AiModel {
  return {
    ...model,
    params: model.params ? { ...model.params } : undefined,
    capabilities: model.capabilities ? model.capabilities.map((item) => ({ ...item })) : undefined,
    supportedEndpointTypes: model.supportedEndpointTypes ? [...model.supportedEndpointTypes] : undefined
  }
}

export function getSystemDefaultModels(): AiModel[] {
  return SYSTEM_DEFAULT_MODELS.map(cloneModel)
}

export function mergeWithSystemDefaultModels(models: AiModel[]): AiModel[] {
  const existingIds = new Set(models.map((model) => String(model.id || '').trim()).filter(Boolean))
  const merged = [...models]
  for (const model of SYSTEM_DEFAULT_MODELS) {
    if (existingIds.has(model.id)) continue
    merged.push(cloneModel(model))
  }
  return merged
}
